### ISSUE TITLE
Invalid dkim signature

### ISSUE THREAD

**Issue by njfox** [panubo/docker-postfix#11]
Hi, docker-postfix is mostly working great but I'm having some issues with DKIM. I have a valid dkim key that I was using on my system's postfix before migrating to this docker image, and I'm mounting it at `/etc/opendkim/dkim.key` in the container and setting `USE_DKIM` to `yes`. The server signs outgoing emails but `mail-tester` is saying the DKIM signature is invalid. I've verified that the `TXT` record is correct.

Do you have any ideas on how to troubleshoot? Do I need to mount any other files for DKIM?

**Comment by trnubo** [comment]
I'd check your `DKIM_SELECTOR` is set correctly. It should match the selector in your TXT record `<selector>._domainkey.<domain>`.

**Comment by njfox** [comment]
Thanks for the response, I've confirmed that it matches (assuming `DKIM_SELECTOR` defaults to `mail` as indicated in the docs, since my TXT record is `mail`._domainkey.domain`). Is there anything else I can do to diagnose?

**Comment by trnubo** [comment]
You will need to look your test results and the email headers to diagnose. We can't provide support for individual configuration issues.

**Comment by njfox** [comment]
The dkim key works just fine on the host’s postfix/dkim install, the issue only exists in this docker container. And given that there is virtually nothing to configure other than turning on dkim (the other default settings should be valid), I suspect that there could be an issue with the docker image. 

Thanks anyway though. I’ll update the issue if I find that the culprit has to do with this image.
