### ISSUE TITLE
RELAYHOST_PASSWORDMAP does not support non standard ports

### ISSUE THREAD

**Issue by aparavind** [panubo/docker-postfix#13]
Unable to set the /etc/postfix/sasl-passwords file when a non-default port is used. 
when a non default port is set .. the format become like 
   the format of the file is 
   `[<domain_name>]:<Port> <user>:<Password>`
However the code is incorrectly mentioned.
```bash
    IFS=',' read -r -a PASSWORDMAP <<< "${RELAYHOST_PASSWORDMAP}"
    for P in "${PASSWORDMAP[@]}"; do
        IFS=':' read -ra MAP <<< "$P"
        HOST=${MAP[0]}
        USER=${MAP[1]}
        PASS=${MAP[2]}
```
Here the USER becomes `<Port> <user>` which is incorrect.

**Comment by macropin** [comment]
Happy to accept a PR for this provided that it does not break the current usage of `RELAYHOST_PASSWORDMAP`

**Comment by macropin** [comment]
This is now supported in #17
