### ISSUE TITLE
buster image is not able to resolve hosts

### ISSUE THREAD

**Issue by spali** [panubo/docker-postfix#16]
I started using the buster image, because of the non default ports I use.
But I had problem, that postfix was not able to resolve the relay hostname.
I think the problem comes from the change to start postfix directly instead of the service script.
The service script does a lot for postfix, because it's instances runs in chroot environment.

quick and dirty, going into the running container and executing the following worked:
```cp /etc/resolv.conf /var/spool/postfix/etc/resolv.conf```

I forked your version to just copy this file in the run script, which works for me.
But I think it would be cleaner to somehow reuse the init script again. Otherwise you have to re-implement all that again.
i.e. init script calls `/usr/lib/postfix/configure-instance.sh` for EACH instance of postfix which does a lot more than just copy the `resolve.conf` file.

**Comment by macropin** [comment]
Thanks for reporting. When I tested this branch I reused the spool directory from the previous version which still had etc populated. I've added `/usr/lib/postfix/configure-instance.sh` to the init script which should be sufficient to resolve this issue.

Can you please test and confirm.

**Comment by spali** [comment]
works now, thank for your great work 👍
