### ISSUE TITLE
Support sender_dependent_relayhost_maps

### ISSUE THREAD

**Issue by trnubo** [panubo/docker-postfix#21]
Adding support for `sender_dependent_relayhost_maps` will allow this container to send to different relay hosts based on the sender.

For example we want to send *@example.com via relay 1 and *@example.net via relay 2.

**Comment by esale** [comment]
It would be great... @trnubo, I'd like to help, but I wouldn't know where to begin. I have some knowledge about docker and bash...

**Comment by macropin** [comment]
This has been added in https://github.com/panubo/docker-postfix/pull/43
