### ISSUE TITLE
For sending only server, we should be able to config mydestination to localhost

### ISSUE THREAD

**Issue by sylvainpiron** [panubo/docker-postfix#29]
Hi,
 
If my receiver server is different than my sending server, we should be able to configure mydestination to localhost.

Thanks in advance,
Best regards.
Sylvain PIRON

**Comment by macropin** [comment]
This is not intended to be used for receiving email for local delivery or end-user email access.

**Comment by sylvainpiron** [comment]
> This is not intended to be used for receiving email for local delivery or end-user email access.

If I'm not mistaken, mydestinitation should be localhost, because you can't send an email to the sender if it is not. Postfix will try do deliver the email instead of sending it to the sender.

Thanks for your work
Best regards
Sylvain.
