### ISSUE TITLE
Add disable_vrfy_command=yes to main.cf

### ISSUE THREAD

**Issue by Sheathan** [panubo/docker-postfix#41]
Vulnerability scanners flag this as a vulnerability because it allows an attacker to find if a mailbox exists on the postfix server or not. This doesn't apply specifically to this container as it's just an SMTP relay and has no mailboxes hosted on it, but it would be an easy addition to the configuration file.

**Comment by jmantz** [comment]
Since this was never looked at, for anybody else who may be interested, just add this line in the Dockerfile with the other postconf -e lines

&& postconf -e disable_vrfy_command=yes \
